const team = [
  {
    name: "Hegel",
    surname: "Minniti",
    age: 23,
    hobby: "Musica, videogames",
    favoriteFood: "Impossibile scegliere",
    favoriteVideoGame: "Palia",
    favoriteFilm: "Sette anime",
    favoriteBook: "Nessuno si salva da solo",
    petName: "Ginger, Yuki, Reneé, Ciccio",
  },
  {
    name: "Martina",
    surname: "Mancuso",
    age: 32,
    city: "Milano",
    hobby: "reading",
    favoriteFood: "indian food",
    favoriteVideoGame: "tomb rider",
    favoriteFilm: "mamma mia",
    favoriteBook: "solo bagaglio a mano",
    petName: "Neve",
  },
  {
    name: "Alessandro",
    surname: "Vaccaro",
    age: 31,
    city: "Pisa",
    hobby: "Wrestling, musica , videogames",
    favoriteFood: "Pizza",
    favoriteVideoGame: "World Of Warcraft",
    favoriteFilm: "Il Miglio Verde",
    favoriteBook: "Il Ciclo dell'Odio",
    petName: "Giorgio",
  },
];
